language: node_js
node_js:
  - "5.0"
  - "5.1"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower -v
  - npm install karma karma-coverage karma-jasmine jasmine-core karma-firefox-launcher
  - bower install
  # - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start tests/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
